basePath: /
info:
  contact: {}
  description: This is a sample server openapi server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "2.0"
paths:
  /adieu:
    get:
      consumes:
      - text/plain
      description: get a adieu message
      parameters:
      - description: Some Name
        in: query
        name: name
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get adieu
  /hello:
    get:
      consumes:
      - text/plain
      description: get a hello message
      parameters:
      - description: Some Name
        in: query
        name: name
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get Hello
swagger: "2.0"
