name: Check for breaking changes in API

on:
  pull_request:
    branches:
      - main


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure spec is up-to-date
        run: |
          make gen-swagger
      - name: Check for breaking changes in API
        id: breaking_changes
        uses: oasdiff/oasdiff-action/breaking@v0.0.19
        with:
          base: https://raw.githubusercontent.com/tjololo/hello-go-openapi/refs/heads/main/docs/swagger.yaml
          revision: docs/swagger.yaml
          fail-on-diff: true
      - name: Generate Action Summary
        id: action_summary
        uses: actions/github-script@v7
        if: always()
        env:
          BREAKING_OUTPUT: ${{ steps.breaking_changes.outputs.breaking }}
        with:
          script: |
            // 1. Prep the output
            const output = `# Breaking API Changes Summary
            #### Check for breaking API changes: 🤖\`${{ steps.breaking_changes.outcome }}\`
            <details><summary>Breaking Changes Output</summary>
            
            \`\`\`\n
            ${process.env.BREAKING_OUTPUT}
            \`\`\`
            
            </details>`;
            
            // 2. Set the output variable
            const fs = require('fs');
            fs.writeFileSync('summary.md', output);
            core.setOutput('summary', output);
      - name: Write Action Summary
        if: always()
        shell: bash
        run: cat summary.md >> $GITHUB_STEP_SUMMARY