name: Check for breaking changes in API

on:
  pull_request:
    branches:
      - main


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure spec is up-to-date
        run: |
          make gen-swagger
      - name: Check for breaking changes in API
        id: breaking_changes
        uses: oasdiff/oasdiff-action/breaking@1c611ffb1253a72924624aa4fb662e302b3565d3
        with:
          base: https://raw.githubusercontent.com/tjololo/hello-go-openapi/refs/heads/main/docs/swagger.yaml
          revision: docs/swagger.yaml
          fail-on: true
          output-to-file: oasdiff.txt
      - name: Generate Action Summary
        id: action_summary
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            // 1. Read the output file
            const fs = require('fs');
            var diffOutput = "No breaking changes found";
            fs.readFileSync('oasdiff.txt', 'utf8', function(err, data) {
              if (err) {
                diffOutput = "Error reading file";
              } else {
                diffOutput = data;
              }
            });
            // 2. Prep the output
            const output = `# Breaking API Changes Summary
            #### Check for breaking API changes: 🤖\`${{ steps.breaking_changes.outcome }}\`
            <details><summary>Breaking Changes Output</summary>
            
            \`\`\`\n
            ${diffOutput}
            \`\`\`
            
            </details>`;
            
            // 3. Set the output variable
            fs.writeFileSync('summary.md', output);
            core.setOutput('summary', output);
      - name: Write Action Summary
        if: always()
        shell: bash
        run: cat summary.md >> $GITHUB_STEP_SUMMARY