name: Bazel push

on:
  push:
    branches:
      - main

jobs:
  test-build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: bazel-contrib/setup-bazel@0.13.0
        with:
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - uses: actions/checkout@v4
      - name: Check formatting
        run: |
          bazel run //:buildifier.check
      - name: Test
        if: false
        run: |
          bazel test //...
      - name: Build
        run: |
          bazel build //...
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to ghcr.io
        run: |
          bazel run //:push --stamp --embed_label=main
