name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test-build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Get version from tags
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - uses: actions/checkout@v5
      - name: Check formatting
        run: |
          bazel run //:buildifier.check
      - name: Test
        if: false
        run: |
          bazel test //...
      - name: Build
        run: |
          bazel build //...
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to ghcr.io
        run: |
          bazel run //:push --stamp --embed_label=${{ steps.version.outputs.tag }}
